# @name post_r2d2
POST http://localhost:8080

text

###
GET http://localhost:8080/{{post_r2d2.response.body.id}}


###
# @name post_bb8
POST http://localhost:9080

text

###
GET http://localhost:9080/{{post_bb8.response.body.id}}

###
# @name post_asp
POST http://localhost:5000

asp

###
GET http://localhost:5000/{{post_asp.response.body.id}}

###
GET http://localhost:5000/date
